### ISSUE TITLE
Async-profiler does not work with the given libc

### ISSUE THREAD

**Issue by pinahar** [jvm-profiling-tools/ap-loader#2]
Getting this error with the latest release

~ # java -jar ap-loader-linux-x64.jar profiler -d 60 1
Exception in thread "main" java.lang.IllegalStateException: Async-profiler does not work with the given libc
        at one.profiler.AsyncProfilerLoader.getLibrarySuffix(AsyncProfilerLoader.java:147)
        at one.profiler.AsyncProfilerLoader.getAsyncProfilerFileName(AsyncProfilerLoader.java:227)
        at one.profiler.AsyncProfilerLoader.isSupported(AsyncProfilerLoader.java:269)
        at one.profiler.AsyncProfilerLoader.checkCommandAvailability(AsyncProfilerLoader.java:645)
        at one.profiler.AsyncProfilerLoader.main(AsyncProfilerLoader.java:666)

I see that a fix has been committed but the release has not been updated maybe?

**Comment by parttimenerd** [comment]
Thanks, I updated it. Can you try again?

**Comment by pinahar** [comment]
Getting a new error now - 
~ # java -jar ap-loader-linux-x64.jar  profiler -d 60 1
Exception in thread "main" java.io.IOException: Cannot run program "/root/.local/share/ap-loader-2.8.3/profiler.sh": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.base/java.lang.Runtime.exec(Runtime.java:592)
        at java.base/java.lang.Runtime.exec(Runtime.java:494)
        at one.profiler.AsyncProfilerLoader.executeProfilerInteractively(AsyncProfilerLoader.java:466)
        at one.profiler.AsyncProfilerLoader.main(AsyncProfilerLoader.java:659)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 5 more
        
I checked and this file does exist. I think the problem is that I'm running this on a distroless java debug image which has busybox shell and not bash. The only way to run the profiler.sh file is to run it with 'sh profiler.sh'.

Is there any good way for me to make this work?

**Comment by parttimenerd** [comment]
I hopefully fixed it.

Please open a new issue the next time.

**Comment by pinahar** [comment]
It works now.
Thanks a lot.
